{
 "title": "SmartBreeze",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Temperature [C°]",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "SmartBreezeDB",
     "rawSql": "SELECT temperature, timestamp FROM SmartBreezeDB.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "Active HVAC",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "SmartBreezeDB",
     "rawSql": "SELECT active_HVAC FROM SmartBreezeDB.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "HVAC history",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 12, "y": 8 },
   "targets": [
    {
     "dataset": "SmartBreezeDB",
     "rawSql": "SELECT active_HVAC, timestamp FROM SmartBreezeDB.temperature LIMIT 50 "
    }
   ]
  },
  {
   "title": "Energy Production [W]",
   "type": "timeseries",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 11 },
   "targets": [
    {
     "dataset": "SmartBreezeDB",
     "rawSql": "SELECT timestamp, sampled, predicted FROM SmartBreezeDB.solar_production LIMIT 50 "
    }
   ]
  }
 ]
}